# 1変量データ

In [2]:
import numpy as np
import scipy as sp

%precision 3

'%.3f'

In [3]:
fish_data = np.array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

## 合計とサンプルサイズ

In [4]:
# 合計値
sp.sum(fish_data)

40

In [5]:
# サンプルサイズ
len(fish_data)

10

## 平均値（期待値)

In [6]:
# 平均値
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.000

In [7]:
# mean関数で平均値
sp.mean(fish_data)

4.000

## 標本分散

In [15]:
# 分散
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.200

In [9]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [10]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [11]:
(fish_data - mu) ** 2

array([ 4.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  4.])

In [12]:
sp.sum((fish_data - mu) ** 2)

12.000

In [14]:
# var関数で分散
sp.var(fish_data, ddof=0)

1.200

## 不偏分散
(個数 - 1)で割ったもの。   
標本分散はデータ個数で割ったもの。

In [16]:
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.333

In [17]:
# var関数で不偏分散
sp.var(fish_data, ddof=1)

1.333

## 標準偏差
分散を平方根をとったもの

In [19]:
# sqrtは平方根をとるもの
sigma = sp.sqrt(sigma_2)
sigma

1.155

In [20]:
# std関数
sp.std(fish_data, ddof = 1)

1.155

## 標準化
データの平均を0に、標準偏差（分散）を1にする変換のこと

In [21]:
# データの平均値を0にする、つまりデータから一律に平均値を引く
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [22]:
# 平均値は0になっていることを確認
sp.mean(fish_data - mu)

0.000

In [24]:
# データの標準偏差を1にする場合は、データを一律に標準偏差で割る
fish_data / sigma

array([ 1.732,  2.598,  2.598,  3.464,  3.464,  3.464,  3.464,  4.33 ,
        4.33 ,  5.196])

In [25]:
# 標準偏差が1になっていることを確認
sp.std(fish_data / sigma, ddof = 1)

1.000

In [26]:
# 両方の変換を合わせると標準化ができる
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [27]:
# 平均値は0
sp.mean(standard)

0.000

In [29]:
# 標準偏差は1
sp.std(standard, ddof=1)

1.000

## その他の統計量

In [30]:
# 最大値
sp.amax(fish_data)

6

In [31]:
# 最小値
sp.amin(fish_data)

2

In [32]:
# 中央値、外れ値に頑強
sp.median(fish_data)

4.000

## scipy.stas と四分位点

In [34]:
from scipy import stats

In [36]:
# 四分位点
fish_data_3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
stats.scoreatpercentile(fish_data_3, 25)

3.000